use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::PathBuf;

const HEADER: &str = r#"// slack-sessions — project registry
//
// Maps short project names to absolute paths. The daemon reads this on
// every DM/mention so changes take effect immediately, no restart needed.
//
// Use in Slack:
//   !start <name> [<message>]   bind a new thread to <name>'s directory
//   !list                       show registered projects + default cwd
//
// Manage via:
//   CLI:    slack-sessions project add|list|remove|set-default
//   Slack:  !add <name> <path>, !remove <name>, !set-default <path>
//
// `default_dir` is the working directory the daemon spawns claude in for
// top-level DMs without a !start prefix; defaults to $HOME if unset.
//
// This file is regenerated by the daemon/CLI on every change. The
// comments above are restored automatically on each write.
"#;

#[derive(Debug, Default, Serialize, Deserialize, Clone)]
pub struct ProjectsRegistry {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default_dir: Option<String>,
    #[serde(default)]
    pub projects: BTreeMap<String, String>,
}

#[allow(dead_code)] // file is shared between cli and daemon; not all methods are used in both
impl ProjectsRegistry {
    pub fn config_path() -> std::io::Result<PathBuf> {
        Ok(crate::config::config_dir()?.join("projects.json"))
    }

    pub fn load() -> std::io::Result<Self> {
        crate::config::load(&Self::config_path()?)
    }

    pub fn save(&self) -> std::io::Result<()> {
        crate::config::save_with_header(&Self::config_path()?, HEADER, self)
    }

    pub fn resolved_default(&self) -> PathBuf {
        if let Some(d) = &self.default_dir {
            return PathBuf::from(d);
        }
        dirs::home_dir().unwrap_or_else(|| PathBuf::from("/"))
    }

    pub fn lookup(&self, name: &str) -> Option<PathBuf> {
        self.projects.get(name).map(PathBuf::from)
    }

    pub fn validate_name(name: &str) -> Result<(), String> {
        if name.is_empty() {
            return Err("name must not be empty".into());
        }
        if !name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
        {
            return Err(format!("name must match [A-Za-z0-9_-]+: {:?}", name));
        }
        Ok(())
    }
}

pub fn expand_tilde(p: &str) -> PathBuf {
    if let Some(rest) = p.strip_prefix("~/") {
        if let Some(home) = dirs::home_dir() {
            return home.join(rest);
        }
    }
    if p == "~" {
        if let Some(home) = dirs::home_dir() {
            return home;
        }
    }
    PathBuf::from(p)
}

/// Expand tilde, canonicalize, and verify it's an existing directory.
/// Returns canonical path on success or human-readable message on failure.
pub fn canonicalize_dir(path_str: &str) -> Result<PathBuf, String> {
    let expanded = expand_tilde(path_str);
    let canonical = std::fs::canonicalize(&expanded)
        .map_err(|_| format!("path does not exist: {}", expanded.display()))?;
    if !canonical.is_dir() {
        return Err(format!("not a directory: {}", canonical.display()));
    }
    Ok(canonical)
}
