use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;
use std::path::PathBuf;

const HEADER: &str = r#"// slack-sessions — allowlist
//
// Slack user IDs that can drive FULL claude sessions on this machine.
// • Listed here:  claude -p --permission-mode bypassPermissions
//                 (full tools, session resume, project registry,
//                  magic commands like !start / !add / !allow)
// • Anyone else:  claude -p --tools ""
//                 (pure-LLM chat — no Read, no Bash, no MCP, no
//                  network egress; bot can answer questions but
//                  cannot touch your filesystem or Slack DMs)
//
// Manage via:
//   CLI:    slack-sessions allow add|list|remove <user-id>
//   Slack:  !allow add|list|remove <user-id>  (allowlisted senders only)
//   Slash:  /slack-sessions:allow [add|list|remove] [user-id]
//
// Find your Slack user_id: in Slack desktop, click your avatar → Profile
// → ⋮ menu → Copy member ID. Format is U… (regular workspace) or W…
// (Enterprise grid), followed by uppercase alphanumerics.
//
// This file is regenerated by the daemon/CLI on every change; the
// comments above are restored automatically on each write.
"#;

#[derive(Debug, Default, Serialize, Deserialize, Clone)]
pub struct Allowlist {
    #[serde(default)]
    pub slack_user_ids: BTreeSet<String>,
}

#[allow(dead_code)] // file is shared between cli and daemon; not all methods are used in both
impl Allowlist {
    pub fn config_path() -> std::io::Result<PathBuf> {
        Ok(crate::config::config_dir()?.join("allowlist.json"))
    }

    pub fn load() -> std::io::Result<Self> {
        crate::config::load(&Self::config_path()?)
    }

    pub fn save(&self) -> std::io::Result<()> {
        crate::config::save_with_header(&Self::config_path()?, HEADER, self)
    }

    pub fn contains(&self, user_id: &str) -> bool {
        self.slack_user_ids.contains(user_id)
    }

    /// Slack user IDs start with `U` (regular) or `W` (Enterprise), followed by
    /// uppercase alphanumerics. Length is typically 9–11 chars but Slack does
    /// not document a strict cap, so we just require >= 9 total.
    pub fn validate_user_id(id: &str) -> Result<(), String> {
        if id.len() < 9 {
            return Err(format!("user id too short: {:?} (expected `U…` or `W…`)", id));
        }
        let mut chars = id.chars();
        match chars.next() {
            Some('U') | Some('W') => {}
            _ => return Err(format!("user id must start with `U` or `W`: {:?}", id)),
        }
        if !chars.all(|c| c.is_ascii_uppercase() || c.is_ascii_digit()) {
            return Err(format!(
                "user id must be uppercase alphanumeric after the leading letter: {:?}",
                id
            ));
        }
        Ok(())
    }
}
